### ISSUE TITLE
Thanks for your codes

### ISSUE THREAD

**Issue by y655r** [roadwide/qqmessageoutput#6]
Hello, Roadwide. Thanks for your codes. I tested your codes. It works on my phone, but does not decrypt on an android pad that has a IMEI. I noticed the QQ app's name is "com.tencent.hd.qq" other than "com.tencent.mobileqq". So I guess the pad's QQ "com.tencent.hd.qq" does not use IMEI as the encryption key. Because some pad may not has a IMEI.  Now I can not login the QQ, just pulled the pad's QQ data(rooted). Do you have any idea about the key in this situation? Thanks.

**Comment by roadwide** [comment]
If the pad’s QQ also uses XOR encryption, we know that XOR encryption is reversible. You can send a piece of known information to someone in QQ, such as a string of numbers, and then use another known number as Key, so that the real encryption key will be solved when the program is used for decryption. This idea is feasible in theory, but I haven't really tried it. In short, XOR encryption means that the original text and the key can be used to solve the original text, and the original text and the cipher text can also be used to solve the key. If the pad's QQ does not use XOR encryption, or its database structure is different from that of the mobile version, then new methods need to be explored.

**Comment by roadwide** [comment]
Sorry, I did not see that you cannot log in to QQ. If this is the case, you may need to find some known plaintext fields in the database to assist in cracking. For example, maybe there may be an encrypted QQ number in the database, but the plaintext of this QQ number is known to us, and then reverse cracking. This is also my assumption, I have not tried it, but because the exclusive OR encryption is reversible, theoretically it can be cracked with violence.

 I have another idea. You can log in to another QQ that you can log in, and then use the method described in my last reply to decrypt the key, and then decrypt the QQ that you cannot log in.

 By the way, Some say the key to the pad may be a MAC address. You can have a try.
